---
title: "Get Started"
author: "Anders H. Jarmund"
date: "`r Sys.Date()`"
bibliography: ALASCA.bib
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%", 
  fig.asp = 0.7,
  fig.width = 12,
  fig.align = "center",
  cache = FALSE,
  external = FALSE
)
```

# Introduction to ALASCA

<script src="js/hideOutput.js"></script>
<style>
.showopt {
  background-color: #004c93;
  color: #FFFFFF; 
  width: 150px;
  height: 20px;
  text-align: center;
  vertical-align: middle !important;
  float: left;
  font-family: sans-serif;
  border-radius: 8px;
}

.showopt:hover {
    background-color: #dfe4f2;
    color: #004c93;
}

.showopttext::before{
  content: "Show/Hide Source"
}

pre.plot {
  background-color: white !important;
}
</style>

The [ALASCA package](https://andjar.github.io/ALASCA) is described in the paper [ALASCA: An R package for longitudinal and cross-sectional analysis of multivariate data by ASCA-based methods.](https://www.frontiersin.org/articles/10.3389/fmolb.2022.962431/full). The paper contains several examples of how the package can be used.

## Installation

```
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")

devtools:install_github(“andjar/ALASCA”, ref = “main”)
```

## Citation
If you have utilized the ALASCA package, please consider citing:

Jarmund AH, Madssen TS and Giskeødegård GF (2022) ALASCA: An R package for longitudinal and cross-sectional analysis of multivariate data by ASCA-based methods. *Front. Mol. Biosci.* 9:962431. doi: 10.3389/fmolb.2022.962431

```
@ARTICLE{10.3389/fmolb.2022.962431,
  AUTHOR={Jarmund, Anders Hagen and Madssen, Torfinn Støve and Giskeødegård, Guro F.},
  TITLE={ALASCA: An R package for longitudinal and cross-sectional analysis of multivariate data by ASCA-based methods},
  JOURNAL={Frontiers in Molecular Biosciences},
  VOLUME={9},
  YEAR={2022},
  URL={https://www.frontiersin.org/articles/10.3389/fmolb.2022.962431},       
  DOI={10.3389/fmolb.2022.962431},      
  ISSN={2296-889X}
}
```


## References